baseURL = "http://example.org/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "My New Site"
description = "Some site description here"
googleAnalytics = ""
paginate = 7
canonifyurls = true

[author]
    name = "Alicia Davis"
    bio = ""
    location = "US"

[[menu.main]]
  weight = 1
  identifier = "categories"
  name = "Categories"
  url = "/categories"
[[menu.main]]
  weight = 2
  identifier = "tags"
  name = "Tags"
  url = "/tags"
